name: iOS pepiline

on:
  push:
    branches: [master]
     
jobs:
  build:
    runs-on: macos-15
    permissions:
      contents: write
      
    steps:
# Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v4
      
# Paso 3: Compilar el proyecto

    - name: Build Cleanup
      run: xcodebuild clean -project Weather.xcodeproj -scheme Weather | xcpretty

    - name: Build Project
      run: xcodebuild -project Weather.xcodeproj -scheme Weather -sdk iphoneos -configuration Release
      
    - name: Git Change Push
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automated Change
