name: iOS pepiline

on:
  push:
    branches: [main]
     
jobs:
  build:
    runs-on: macos-15
    permissions:
      contents: write
      
    steps:
# Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: swift package resolve
      
# Paso 3: Compilar el proyecto
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app

    - name: Build Project
      run: xcodebuild -project Weather.xcodeproj -scheme Weather -sdk iphoneos -configuration Release
      
    - name: Git Change Push
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automated Change
